In [43]:
import numpy as np

In [44]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
y = np.ones(10, dtype='uint8')
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [46]:
a = x*y[:,np.newaxis]
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
b = a.transpose()
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [48]:
c = np.maximum(a,b)
c

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [2, 2, 2, 3, 4, 5, 6, 7, 8, 9],
       [3, 3, 3, 3, 4, 5, 6, 7, 8, 9],
       [4, 4, 4, 4, 4, 5, 6, 7, 8, 9],
       [5, 5, 5, 5, 5, 5, 6, 7, 8, 9],
       [6, 6, 6, 6, 6, 6, 6, 7, 8, 9],
       [7, 7, 7, 7, 7, 7, 7, 7, 8, 9],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [49]:
d = np.flip(c, axis=0)
d

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 9],
       [7, 7, 7, 7, 7, 7, 7, 7, 8, 9],
       [6, 6, 6, 6, 6, 6, 6, 7, 8, 9],
       [5, 5, 5, 5, 5, 5, 6, 7, 8, 9],
       [4, 4, 4, 4, 4, 5, 6, 7, 8, 9],
       [3, 3, 3, 3, 4, 5, 6, 7, 8, 9],
       [2, 2, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
e = np.flip(d, axis=1)
e

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 8, 7, 7, 7, 7, 7, 7, 7, 7],
       [9, 8, 7, 6, 6, 6, 6, 6, 6, 6],
       [9, 8, 7, 6, 5, 5, 5, 5, 5, 5],
       [9, 8, 7, 6, 5, 4, 4, 4, 4, 4],
       [9, 8, 7, 6, 5, 4, 3, 3, 3, 3],
       [9, 8, 7, 6, 5, 4, 3, 2, 2, 2],
       [9, 8, 7, 6, 5, 4, 3, 2, 1, 1],
       [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [51]:
f = np.flip(c, axis=1)
f

array([[9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5, 4, 3, 2, 1, 1],
       [9, 8, 7, 6, 5, 4, 3, 2, 2, 2],
       [9, 8, 7, 6, 5, 4, 3, 3, 3, 3],
       [9, 8, 7, 6, 5, 4, 4, 4, 4, 4],
       [9, 8, 7, 6, 5, 5, 5, 5, 5, 5],
       [9, 8, 7, 6, 6, 6, 6, 6, 6, 6],
       [9, 8, 7, 7, 7, 7, 7, 7, 7, 7],
       [9, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [52]:
g = np.array((c,d,e,f))
g

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [2, 2, 2, 3, 4, 5, 6, 7, 8, 9],
        [3, 3, 3, 3, 4, 5, 6, 7, 8, 9],
        [4, 4, 4, 4, 4, 5, 6, 7, 8, 9],
        [5, 5, 5, 5, 5, 5, 6, 7, 8, 9],
        [6, 6, 6, 6, 6, 6, 6, 7, 8, 9],
        [7, 7, 7, 7, 7, 7, 7, 7, 8, 9],
        [8, 8, 8, 8, 8, 8, 8, 8, 8, 9],
        [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [8, 8, 8, 8, 8, 8, 8, 8, 8, 9],
        [7, 7, 7, 7, 7, 7, 7, 7, 8, 9],
        [6, 6, 6, 6, 6, 6, 6, 7, 8, 9],
        [5, 5, 5, 5, 5, 5, 6, 7, 8, 9],
        [4, 4, 4, 4, 4, 5, 6, 7, 8, 9],
        [3, 3, 3, 3, 4, 5, 6, 7, 8, 9],
        [2, 2, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [9, 8, 8, 8, 8, 8, 8, 8, 8, 8],
        [9, 8, 7, 7, 7, 7, 7, 7, 7, 7],
        [9, 8, 7, 6, 6, 6, 6, 6, 6, 6],
        [9, 8, 7, 6, 5, 5, 5, 5, 5, 

In [53]:
g.shape

(4, 10, 10)

In [54]:
np.max(g, axis=0)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 8, 8, 8, 8, 8, 8, 8, 8, 9],
       [9, 8, 7, 7, 7, 7, 7, 7, 8, 9],
       [9, 8, 7, 6, 6, 6, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 6, 6, 6, 7, 8, 9],
       [9, 8, 7, 7, 7, 7, 7, 7, 8, 9],
       [9, 8, 8, 8, 8, 8, 8, 8, 8, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [55]:
g = np.array((c,d,e,f))
h = np.zeros(g.shape,dtype='uint8')
h[g==np.max(g, axis=0)]=1
h[g!=np.max(g, axis=0)]=0
h

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 

In [66]:
i = np.zeros(h.shape, dtype='uint8')
i = np.sum(h, axis=0)
j = np.divide(g*h,i) 
j

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 3.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 2.66666667, 4.5       ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 2.33333333, 4.        , 4.5       ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 2.        , 3.5       , 4.        , 4.5       ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         1.66666667, 3.        , 3.5       , 4.        , 4.5       ],
        [0.        , 0.        , 0.        , 0.        , 1.66666667,
         1.66666667, 3.        , 3.5       , 4.        , 4.5       ],
        [0.        , 0.        , 0.        , 2.        , 3.        ,
         3.        , 2.        , 3.5       , 4.        , 4.5       ],
        [0.        , 0.    

In [67]:
k = np.sum(j, axis=0)
k

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 8., 8., 8., 8., 8., 8., 8., 8., 9.],
       [9., 8., 7., 7., 7., 7., 7., 7., 8., 9.],
       [9., 8., 7., 6., 6., 6., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 5., 5., 6., 7., 8., 9.],
       [9., 8., 7., 6., 6., 6., 6., 7., 8., 9.],
       [9., 8., 7., 7., 7., 7., 7., 7., 8., 9.],
       [9., 8., 8., 8., 8., 8., 8., 8., 8., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [69]:
g = np.array((c,d,e,f))

h = np.zeros(g.shape,dtype='uint8')
h[g==np.max(g, axis=0)]=1
h[g!=np.max(g, axis=0)]=0

i = np.zeros(h.shape, dtype='uint8')
i = np.sum(h, axis=0)
j = np.divide(g*h,i)

k = np.sum(j, axis=0)

print('g',g.shape)
print('h',h.shape)
print('i',i.shape)
print('j',j.shape)
print('k',k.shape)

g (4, 10, 10)
h (4, 10, 10)
i (10, 10)
j (4, 10, 10)
k (10, 10)


In [77]:
z = np.array(255.999)
z = z.astype('uint8')
z

array(255, dtype=uint8)

In [78]:
l = np.array((5,5,5,5,5,5,5,5))

In [79]:
l

array([5, 5, 5, 5, 5, 5, 5, 5])

In [80]:
l.shape

(8,)

In [81]:
g.shape

(4, 10, 10)

In [82]:
g.shape[1:]

(10, 10)