# Understanding Data Types

### Let's practice Python and Numpy with Jupyter Notebook

start with the basics

In [1]:
#iterate using range
result = 0
for i in range(100):
    result += 1

In [2]:
#assign a new value to a variable
x=4
print(type(x))
x='four'
print(type(x))

<class 'int'>
<class 'str'>


Let's play with Lists

In [3]:
#assign a range to a list
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
print(type(L))
print(type(L[0]))

<class 'list'>
<class 'int'>


In [5]:
L2 = [str(c) for c in L]
print(type(L2))
print(type(L2[0]))
L2

<class 'list'>
<class 'str'>


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
#Create a heterogeneous list and output the type
L3 = [True, "2", 3.0, 4]
[type(item)for item in L3]

[bool, str, float, int]

In [7]:
#Create a Python array
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Let's start working with numpy

In [8]:
import numpy as np

In [9]:
# Create a numpy integer array

np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [10]:
# The array will automatically set the data type to the least complex required to represent the data

np.array([3.14, 1, 5, 4])

array([3.14, 1.  , 5.  , 4.  ])

In [11]:
# Or you can explicitely set the data type using the keywork dtype. ex float32, int, etc.

np.array([1,4,2,5,3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [12]:
# You can have multidimensional lists also

A = np.array([range(i, i + 3) for i in [2,4,6]])
print(A)
print(A[2][1])

[[2 3 4]
 [4 5 6]
 [6 7 8]]
7


### Let's create some basic arrays to work with

In [13]:
# Create a 1 x 10 array of zeros

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# Create a 3 x 5 array of floating-point ones

np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Create an 4 x 6 array filled with any number

np.full((4,6), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
# Create an array of 6 linearly spaced values between 4 and 22

np.linspace(4, 22, 6)

array([ 4. ,  7.6, 11.2, 14.8, 18.4, 22. ])

In [17]:
# Create a 5 x 5 array of uniformly distributed random values between 0 and 10
# np.random.random generates uniformly distributed between 0 and 1, multiply by n to get the max you wish.

10*np.random.random((5,5))

array([[1.65767017, 2.11476283, 8.87697832, 7.7004513 , 7.89119285],
       [9.30667198, 5.30134231, 8.6980854 , 0.59655107, 1.43794888],
       [5.606891  , 3.02961129, 3.1429766 , 7.77864652, 1.28594655],
       [0.39650014, 9.37056255, 9.39417997, 0.4050304 , 4.42025374],
       [2.9727795 , 3.6444096 , 5.90778174, 7.60855035, 4.99791418]])

In [18]:
#Create a 5 x 3 array of normally distributed random numbers centered on 0 with a standard deviation of 1

np.random.normal(0,1,(5,3))

array([[-0.04975484,  2.29092082, -0.42457519],
       [-0.97847703, -0.71087944,  0.37993564],
       [-0.43090764, -0.50762557, -0.55094837],
       [-0.91473017, -0.14447865, -1.00017462],
       [-0.70276701,  1.62871877,  1.17950696]])

In [19]:
# Create a 3 x 3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Create a 5 x 5 matrix of random integers between 0 and 100

np.random.randint(0,100,(3,3))

array([[56, 34, 91],
       [49, 31, 17],
       [85,  0,  5]])

In [21]:
# Create an uninitialized array of 3 integers
# The values will be whatever happens to already exist at that memory

np.empty(5)

array([0. , 0.5, 1. , 1.5, 2. ])

# --------------- Data types in Numpy ---------------


In [22]:
"""The available data types in python are:

bool_ 	Boolean (True or False) stored as a byte
int_ 	Default integer type (same as C long; normally either int64 or int32)
intc 	Identical to C int (normally int32 or int64)
intp 	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8 	Byte (-128 to 127)
int16 	Integer (-32768 to 32767)
int32 	Integer (-2147483648 to 2147483647)
int64 	Integer (-9223372036854775808 to 9223372036854775807)
uint8 	Unsigned integer (0 to 255)
uint16 	Unsigned integer (0 to 65535)
uint32 	Unsigned integer (0 to 4294967295)
uint64 	Unsigned integer (0 to 18446744073709551615)
float_ 	Shorthand for float64.
float16 	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32 	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64 	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_ 	Shorthand for complex128.
complex64 	Complex number, represented by two 32-bit floats
complex128 	Complex number, represented by two 64-bit floats


'b' 	Byte 	np.dtype('b')
'i' 	Signed integer 	np.dtype('i4') == np.int32
'u' 	Unsigned integer 	np.dtype('u1') == np.uint8
'f' 	Floating point 	np.dtype('f8') == np.int64
'c' 	Complex floating point 	np.dtype('c16') == np.complex128
'S', 'a' 	String 	np.dtype('S5')
'U' 	Unicode string 	np.dtype('U') == np.str_
'V' 	Raw data (void) 	np.dtype('V') == np.void
""";

In [23]:
# Data type can be specified at array creation with either a string or calling the numpy object

A = np.zeros((10,10), dtype = 'int16')
B = np.zeros((10,10), dtype = np.int16)
A == B

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])