# Computation on Numpy Arrays : Universal Functions (ufuncs)

In [1]:
# Loops are slow, try to use vectorized computations with numpy arrays

import numpy as np

np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1,10, size=5)
reciprocals = compute_reciprocals(values)
print(values)
print(reciprocals)

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]


In [2]:
# Here is how to use the '%timeit', one of the universal functions(ufuncs) in python
# Notice that the size of elements in the array have virtually no effect on the runt time
# Optimization of the code to minizime loops is essential


big_array1 = np.random.randint(1,10, size=1000)
big_array2 = np.random.randint(1,(2**33), size=1000)
bigger_array1 = np.random.randint(1,10, size=1000000)
bigger_array2 = np.random.randint(1,(2**33), size=1000000)
%timeit compute_reciprocals(big_array1)
%timeit compute_reciprocals(big_array2)
%timeit compute_reciprocals(bigger_array1)
%timeit compute_reciprocals(bigger_array2)


1.83 ms ± 78.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.81 ms ± 75.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.82 s ± 44.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.77 s ± 37.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
# Using ufuncs, the static typing of numpy arrays allows operations like this to be pushed into the compiled layer
# underlying the python interface.  This bypasses all of the conversion between Python and C
# ***MUCH FASTER***

%timeit (1/big_array1)
%timeit (1/big_array2)
%timeit (1/bigger_array1)
%timeit (1/bigger_array2)

2.18 µs ± 36.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.21 µs ± 51.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.26 ms ± 8.12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.3 ms ± 44.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
# all of the basic mathematical operations can be applied in this way
x = np.arange(1,10).reshape((3,3))
print(x, '\n')
y = 2*x
print(y, '\n')
z = x*y
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


# Exploring ufuncs

### Array Arithmetic

In [5]:
x = np.arange(4)
print(" x      = ", x, '\n')
print(" x + 5  = ", x + 5, '\n')    
print(" x - 5  = ", x - 5, '\n')
print(" x * 2  = ", x * 2, '\n')
print(" x / 2  = ", x / 2, '\n')
print(" x //2  = ", x // 2, '\n')  # Floor Division
print("-x      = ", -x, '\n')
print(" x % 2  = ", x % 2, '\n')

 x      =  [0 1 2 3] 

 x + 5  =  [5 6 7 8] 

 x - 5  =  [-5 -4 -3 -2] 

 x * 2  =  [0 2 4 6] 

 x / 2  =  [0.  0.5 1.  1.5] 

 x //2  =  [0 0 1 1] 

-x      =  [ 0 -1 -2 -3] 

 x % 2  =  [0 1 0 1] 



In [6]:
# The order of operations is respected

-(.25 * x + 1) **2

array([-1.    , -1.5625, -2.25  , -3.0625])

In [7]:
# the arithmetic operators are a wrapper for numpy method ufuncs that accept an array and a quantity

A = np.add(x , 2)
print(x)
print(A)

[0 1 2 3]
[2 3 4 5]


In [8]:
# Here are the list of ufuncs and their equivalents

"""
+ 	np.add 	Addition (e.g., 1 + 1 = 2)
- 	np.subtract 	Subtraction (e.g., 3 - 2 = 1)
- 	np.negative 	Unary negation (e.g., -2)
* 	np.multiply 	Multiplication (e.g., 2 * 3 = 6)
/ 	np.divide 	Division (e.g., 3 / 2 = 1.5)
// 	np.floor_divide 	Floor division (e.g., 3 // 2 = 1)
** 	np.power 	Exponentiation (e.g., 2 ** 3 = 8)
% 	np.mod 	Modulus/remainder (e.g., 9 % 4 = 1)

""";

In [9]:
# Python recognizes the built-in python commands as well as the 
# The two methods time the same.

x = np.array([-2, -1, 0, 1 , 2])
x = np.arange(-10000,10000)
negx = -1*x[::-1]
negx = negx.copy() 
print(x)
print(negx)

%timeit abs(x)
%timeit np.absolute(x)

[-10000  -9999  -9998 ...   9997   9998   9999]
[-9999 -9998 -9997 ...  9998  9999 10000]
10.5 µs ± 387 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
10.2 µs ± 54.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
# Absolute values work on complex numbers too

x = np.array([4-4j, 4-3j, 2+0j, 0+1J])
print(x)
print(np.abs(x)) # returns the MAGNITUDE of the complex number (a**2 + b**2 = c**c)

[4.-4.j 4.-3.j 2.+0.j 0.+1.j]
[5.65685425 5.         2.         1.        ]


### Trigonometric Functions

In [11]:
# Trig functions are as follows

theta = np.linspace(0,np.pi, 3)
print("theta.        =", theta, '\n')
print("sin(theta)    =", np.sin(theta), '\n')
print("cos(theta)    =", np.cos(theta), '\n')
print("tan(theta)    =", np.tan(theta))

theta.        = [0.         1.57079633 3.14159265] 

sin(theta)    = [0.0000000e+00 1.0000000e+00 1.2246468e-16] 

cos(theta)    = [ 1.000000e+00  6.123234e-17 -1.000000e+00] 

tan(theta)    = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [12]:

x = np.array([0,1,0])
print("x.            =", theta, '\n')
print("arcsin(x)    =", np.arcsin(x), '\n')
print("arccos(x)    =", np.arccos(x), '\n')
print("arctan(x)    =", np.arctan(x))


x.            = [0.         1.57079633 3.14159265] 

arcsin(x)    = [0.         1.57079633 0.        ] 

arccos(x)    = [1.57079633 0.         1.57079633] 

arctan(x)    = [0.         0.78539816 0.        ]


### Numpy has ufuncs for Exponents and Logarithms

In [13]:
x = [1,2,3]

print("x    =", x,'\n')
print("e^x  =", np.exp(x),'\n')
print("2^x  =", np.exp2(x),'\n')
print("3^x  =", np.power(3,x),'\n') # 'np.power(x,y)' raises x to the power of y

x    = [1, 2, 3] 

e^x  = [ 2.71828183  7.3890561  20.08553692] 

2^x  = [2. 4. 8.] 

3^x  = [ 3  9 27] 



In [14]:
x = [1,2,8,100]

print("x       =", x,'\n')
print("ln(x)   =", np.log(x),'\n')
print("log2(x) =", np.log2(x),'\n')
print("log10(x)=", np.log10(x),'\n')

x       = [1, 2, 8, 100] 

ln(x)   = [0.         0.69314718 2.07944154 4.60517019] 

log2(x) = [0.         1.         3.         6.64385619] 

log10(x)= [0.         0.30103    0.90308999 2.        ] 



In [15]:
# There are also some specialized log functions for maintaining precision with very small values

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x),'\n')
print("log(1 + x) =", np.log1p(x),'\n')

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092] 

log(1 + x) = [0.         0.0009995  0.00995033 0.09531018] 



### Specialized ufuncs

In [16]:
# scipy has some specialized ufuncs for statistical analysis
from scipy import special

x = [1, 5, 10]

print("gamma(x)     =", special.gamma(x),'\n')
print("ln|gamma(x)| =", special.gammaln(x),'\n')
print("beta(x, 2)   =", special.beta(x, 2),'\n')



gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05] 

ln|gamma(x)| = [ 0.          3.17805383 12.80182748] 

beta(x, 2)   = [0.5        0.03333333 0.00909091] 



In [17]:
# Error function (integral of Gaussian)
# its complement, and its inverse

x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x),'\n')
print("erfc(x) =", special.erfc(x),'\n')
print("erfinv(x) =", special.erfinv(x),'\n')

erf(x)  = [0.         0.32862676 0.67780119 0.84270079] 

erfc(x) = [1.         0.67137324 0.32219881 0.15729921] 

erfinv(x) = [0.         0.27246271 0.73286908        inf] 



# Advanced Ufunc Features

### Assigning result to a function

In [18]:
# The output of a ufunc can be specified inside the function without assigning to a variable.
# To do this you must create an appropriately sized array to place the result in.

x = np.arange(5)
y = np.empty(5)
np.multiply(x,10, out=y)
print(x)
print(y)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [19]:
# The results of the function can be assigned with slice formatting also

y = np.zeros(10)
np.power(2,x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
