# ------------ The Basics of Numpy Arrays ------------------

### What are the attributes of a Numpy Array?

In [1]:
# Let's look at some basic properties of numpy arrays

# ndim - the number of dimensions of the array
# shape - the length of each dimension
# size - the total number of elements in the array

import numpy as np

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(4,8))
x3 = np.random.randint(10, size=(3,3,4))

D = [x1,x2,x3]
for i in D:
    print("ndim                = ", i.ndim)
    print("shape               = ", i.shape)
    print("size                = ", i.size)
    print("dtype               = ", i.dtype)
    print("size per entry      = ", i.itemsize, "bytes")
    print("total size of array = ", i.nbytes, "bytes \n")
    print(i,'\n')
    print('------------------------------------------------')

ndim                =  1
shape               =  (6,)
size                =  6
dtype               =  int64
size per entry      =  8 bytes
total size of array =  48 bytes 

[3 4 0 4 3 4] 

------------------------------------------------
ndim                =  2
shape               =  (4, 8)
size                =  32
dtype               =  int64
size per entry      =  8 bytes
total size of array =  256 bytes 

[[6 3 4 5 8 9 2 5]
 [7 3 1 5 7 1 3 6]
 [6 3 1 0 9 6 3 2]
 [7 4 1 9 4 6 3 9]] 

------------------------------------------------
ndim                =  3
shape               =  (3, 3, 4)
size                =  36
dtype               =  int64
size per entry      =  8 bytes
total size of array =  288 bytes 

[[[1 9 7 8]
  [0 3 6 9]
  [9 8 5 4]]

 [[1 7 1 1]
  [8 5 7 8]
  [6 6 2 2]]

 [[2 4 0 3]
  [4 4 3 6]
  [8 8 3 9]]] 

------------------------------------------------


### Array Indexing of single elements

In [2]:
# Access elements of a 1-D array with a bracketted integer

print(x1)
print(x1[1])
print(x1[3])

[8 5 3 4 2 9]
5
4


In [3]:
# Use negative integers to access the array from the end
# Notice the negative index starts counting from -1 
# ***'-0' IS READ AS '0' AND WILL RETURN THE FIRST ELEMENT!!!***

print(x1[-1])
print(x1[-4])

9
3


In [4]:
# Access the elements of a multidimensional array using comma seperated tuples

print(x2)
print(x2[2,5],'\n')
print(x3)
print(x3[2,2,2])


[[0 5 1 3 6 8 7 5]
 [9 0 6 1 7 6 9 1]
 [7 9 7 8 5 9 5 7]
 [2 2 6 7 9 5 5 2]]
9 

[[[5 6 9 2]
  [6 6 2 8]
  [4 5 3 2]]

 [[5 0 5 7]
  [0 8 4 9]
  [9 0 4 0]]

 [[4 0 0 2]
  [5 0 1 8]
  [0 3 1 4]]]
1


In [3]:
# Accessing arrays from the end works the same as with 1-D arrays

print(x2)
print(x2[-3,-4],'\n')
print(x3)
print(x3[-1,-2,-1])


[[6 3 4 5 8 9 2 5]
 [7 3 1 5 7 1 3 6]
 [6 3 1 0 9 6 3 2]
 [7 4 1 9 4 6 3 9]]
7 

[[[1 9 7 8]
  [0 3 6 9]
  [9 8 5 4]]

 [[1 7 1 1]
  [8 5 7 8]
  [6 6 2 2]]

 [[2 4 0 3]
  [4 4 3 6]
  [8 8 3 9]]]
6


In [6]:
# You can modify the elements of an array by index

print(x2)
x2[2,1] = 80
print(x2)

[[0 5 1 3 6 8 7 5]
 [9 0 6 1 7 6 9 1]
 [7 9 7 8 5 9 5 7]
 [2 2 6 7 9 5 5 2]]
[[ 0  5  1  3  6  8  7  5]
 [ 9  0  6  1  7  6  9  1]
 [ 7 80  7  8  5  9  5  7]
 [ 2  2  6  7  9  5  5  2]]


### One Dimensional Subarrays : Array Slicing

In [7]:
# Using the':' character lets you select elements from an array
# x[start:stop(:step)]
# With only one colon the slice defaults to star:stop
# Leaving start or stop blank defaults to the beginning or end of an array respectively
# The slice is BEFORE the stop index

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# With only one colon the slice defaults to star:stop
# Leaving start or stop blank defaults to the beginning or end of an array respectively
# The slice is BEFORE the stop index

print(x[:5])
print(x[0:5],'\n')
print(x[5:])
print(x[5:len(x)])

[0 1 2 3 4]
[0 1 2 3 4] 

[5 6 7 8 9]
[5 6 7 8 9]


In [9]:
# Specify a start and stop index slices an array from the middle

print(x[2:7])
print(x[3:9])

[2 3 4 5 6]
[3 4 5 6 7 8]


In [10]:
# When using two colons without specifying start and stop
# Defaults to starting from the first elemenet and every next element one 'step' away

print(x[::2])
print(x[::3])

[0 2 4 6 8]
[0 3 6 9]


In [11]:
# Negatives for the Start and Stop value simply start counting from the end of the array
# Negatives for the 'step' value print the values in reverse
# x[start:stop:(+step] : [_,_,START INDEX,-,-,-,-,-,>|,STOP INDEX,_,_,_]

print(x[0:-3:1])
print(x[0:7:1])
print(x[8::-1])

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]
[8 7 6 5 4 3 2 1 0]


In [12]:
# x[start:stop:(-step] : [_,_,STOP INDEX,|<-,-,-,-,-,-,START INDEX,_,_,_]
# For negative step values you must leave the stop value blank to include the print(x[8::-1])

print(x[8:0:-1])
print(x[8::-1])

[8 7 6 5 4 3 2 1]
[8 7 6 5 4 3 2 1 0]


In [13]:
# If the stop index comes before the start index or
# with negative steps the stop index comes after the start index the slice is returned empty

print(x[7:1:1])
print(x[5:7:-1])

[]
[]


### Multi Dimensional Sub Arrays

In [14]:
# With Slicing works the same with n-D arrays as it does with 1-D arrays.

x2

array([[ 0,  5,  1,  3,  6,  8,  7,  5],
       [ 9,  0,  6,  1,  7,  6,  9,  1],
       [ 7, 80,  7,  8,  5,  9,  5,  7],
       [ 2,  2,  6,  7,  9,  5,  5,  2]])

In [15]:
# Second to Third Rows, Third to Seventh Column
x2[1:3,2:7]

array([[6, 1, 7, 6, 9],
       [7, 8, 5, 9, 5]])

In [16]:
# Every Other Row, Every Thirsd Column
x2[::2,::3]

array([[0, 3, 7],
       [7, 8, 5]])

In [17]:
# A single ':' will return the full row or column
# Ommiting the comma seperator and the column index automatically returns the full column

print(x2[3,:])
print(x2[3])
print(x2[:,5])

[2 2 6 7 9 5 5 2]
[2 2 6 7 9 5 5 2]
[8 6 9 5]


In [18]:
# Using '=' to assign a value from an array to a variable ***LINKS THE VARIABLE TO THE ARRAY***

x2 = np.random.randint(10, size=(4,8))
print(x2)
x2_sub = x2[1:3,2:6]
print(x2_sub)
x2_sub[:,:] = 44
print(x2_sub)
print(x2)

[[5 4 4 5 6 0 7 0]
 [0 4 1 1 9 1 3 3]
 [6 1 5 2 5 4 3 9]
 [9 8 2 4 2 9 4 0]]
[[1 1 9 1]
 [5 2 5 4]]
[[44 44 44 44]
 [44 44 44 44]]
[[ 5  4  4  5  6  0  7  0]
 [ 0  4 44 44 44 44  3  3]
 [ 6  1 44 44 44 44  3  9]
 [ 9  8  2  4  2  9  4  0]]


In [19]:
# To create an UNLINKED copy you must use the (array).copy() method

x2 = np.random.randint(10, size=(4,8))
print(x2)
x2_sub = x2[1:3,2:6].copy()
print(x2_sub)
x2_sub[:,:] = 44
print(x2_sub)
print(x2)

[[9 8 8 8 0 0 7 5]
 [9 6 5 5 6 5 4 0]
 [1 4 0 0 0 8 0 6]
 [4 1 8 9 5 6 5 5]]
[[5 5 6 5]
 [0 0 0 8]]
[[44 44 44 44]
 [44 44 44 44]]
[[9 8 8 8 0 0 7 5]
 [9 6 5 5 6 5 4 0]
 [1 4 0 0 0 8 0 6]
 [4 1 8 9 5 6 5 5]]


In [20]:
grid1by9 = np.arange(1,10)
print(grid1by9, '\n')
grid3by3 = grid1by9.reshape(3,3)
print(grid3by3)


[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
x = np.array([1,2,3])



In [22]:
# Create a row vector:

# via '.reshape'
y = x.reshape(1,len(x))
print(y)

# via 'newaxis'
y[np.newaxis,:]
print(y)

[[1 2 3]]
[[1 2 3]]


In [23]:
# Create a new column vector

# via '.reshape'
y = x.reshape(len(x),1)
print(y)

# via 'np.newaxis'
y[:,np.newaxis]
print(y)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


### Concatenation of Arrays

In [24]:
# You can use 'np.concatenate' to join arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [25]:
# You can concatenate as many arrays as you wish
z = np.array([99,99,99])
grid = np.concatenate([x,y,z])
print(grid)
grid = np.concatenate([[x],[y],[z]])
print(grid)

[ 1  2  3  3  2  1 99 99 99]
[[ 1  2  3]
 [ 3  2  1]
 [99 99 99]]


In [26]:
# You  can concatenate n-D arrays as wellat once

# Wihtout specifying a value for the axis keyword it will be done in the the first Axis
a = np.concatenate([[grid,grid],[grid,grid]])
print (a, a.shape,'\n')

# You can specify the axis with the 'axis=' keyword
b = np.concatenate([grid,grid], axis=0)
print (b,b.shape)


[[[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]

 [[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]

 [[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]

 [[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]] (4, 3, 3) 

[[ 1  2  3]
 [ 3  2  1]
 [99 99 99]
 [ 1  2  3]
 [ 3  2  1]
 [99 99 99]] (6, 3)


In [27]:
# You can specify to concatenate in whatever axis up to the number of dimensions in the array

c = np.concatenate([grid,grid], axis=1)
print (c)

[[ 1  2  3  1  2  3]
 [ 3  2  1  3  2  1]
 [99 99 99 99 99 99]]


### Splitting of Arrays

In [28]:
# to use 'np.split(array,tuple)' specify the array and in the tuple specify the index of where to split.
# np.split() produces multiple arrays broken by the split index

x = [1,2,3,99,99,3,2,1]
print(x)

x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]


In [29]:
# 'np.vsplit()' splits the array at a row index, along the first axis (axis=0)

upper,lower = np.vsplit(a,[1])
print(upper,'\n\n',lower,'\n')

[[[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]] 

 [[[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]

 [[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]

 [[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]] 



In [30]:
# 'np.hsplit()' splits the array at a column index, along the second axis(axis=0)

print(grid,'\n\n')

left, right = np.hsplit(a,[1])
print(upper,'\n\n',lower,'\n')

[[ 1  2  3]
 [ 3  2  1]
 [99 99 99]] 


[[[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]] 

 [[[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]

 [[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]

 [[ 1  2  3]
  [ 3  2  1]
  [99 99 99]]] 

