In [1]:
import numpy as np

In [2]:
np.arange(256)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [3]:
h = np.zeros(256*3)

In [4]:
h.shape

(768,)

In [6]:
h.shape[0]/3

256.0

In [9]:
for i in range(3):
    print(h[(i*256):(i*256+256)].shape)

(256,)
(256,)
(256,)


In [10]:
import os

a = os.walk('/Users/anthonyesposito/Pictures/macroni/Rosasite_w_Conacalcite/1/check/JPG')
for root, dirs, files in a:
    b = files
    
print(files)

['DSCF6938.jpg', 'DSCF6939.jpg', 'DSCF6929.jpg', 'DSCF6928.jpg', 'DSCF6949.jpg', 'DSCF6948.jpg', 'DSCF6951.jpg', 'DSCF6945.jpg', 'DSCF6944.jpg', 'DSCF6950.jpg', 'DSCF6946.jpg', 'DSCF6947.jpg', 'DSCF6943.jpg', 'DSCF6942.jpg', 'DSCF6940.jpg', 'DSCF6941.jpg', 'DSCF6932.jpg', 'DSCF6926.jpg', 'DSCF6927.jpg', 'DSCF6933.jpg', 'DSCF6925.jpg', 'DSCF6931.jpg', 'DSCF6930.jpg', 'DSCF6924.jpg', 'DSCF6920.jpg', 'DSCF6934.jpg', 'DSCF6935.jpg', 'DSCF6921.jpg', 'DSCF6937.jpg', 'DSCF6923.jpg', 'DSCF6922.jpg', 'DSCF6936.jpg']


In [31]:
for i in range(len(files)):
    a = filter(str.isdigit, files[i])
    files[i] = int(''.join(a))

    print(type(files[i]),files[i])

<class 'int'> 6938
<class 'int'> 6939
<class 'int'> 6929
<class 'int'> 6928
<class 'int'> 6949
<class 'int'> 6948
<class 'int'> 6951
<class 'int'> 6945
<class 'int'> 6944
<class 'int'> 6950
<class 'int'> 6946
<class 'int'> 6947
<class 'int'> 6943
<class 'int'> 6942
<class 'int'> 6940
<class 'int'> 6941
<class 'int'> 6932
<class 'int'> 6926
<class 'int'> 6927
<class 'int'> 6933
<class 'int'> 6925
<class 'int'> 6931
<class 'int'> 6930
<class 'int'> 6924
<class 'int'> 6920
<class 'int'> 6934
<class 'int'> 6935
<class 'int'> 6921
<class 'int'> 6937
<class 'int'> 6923
<class 'int'> 6922
<class 'int'> 6936


In [39]:
a = np.array(files)

In [40]:
np.where( a == 6936)

(array([31]),)

In [41]:
a.astype('int64')

array([6938, 6939, 6929, 6928, 6949, 6948, 6951, 6945, 6944, 6950, 6946,
       6947, 6943, 6942, 6940, 6941, 6932, 6926, 6927, 6933, 6925, 6931,
       6930, 6924, 6920, 6934, 6935, 6921, 6937, 6923, 6922, 6936])

In [113]:
a = np.array([[ 1,  2,  3,  4], 
              [ 5,  6,  7,  8], 
              [ 9, 10, 11, 12], 
              [13, 14, 15, 16]])
b = np.argsort(a, axis=1)
b

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [10]:
d = 5
e = [d]
print(e)

[5]


In [6]:
e.append(8)

In [7]:
e

[5, 5, 8]

In [71]:
f = list(range(10))
print(f)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [72]:
for i in f[1:]:
    print(i)

1
2
3
4
5
6
7
8
9


In [11]:
e.remove(5)

In [12]:
e

[]

In [13]:
len(e)

0

In [14]:
a

NameError: name 'a' is not defined

In [16]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
g = [3,1]
a[g,...]

array([[13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [18]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [68]:
h = np.ravel(a, order='F')
h.shape[0]

16

In [69]:
for i in range(h.shape[0]-1,-1,-1):
    print(h[i])

16
12
8
4
15
11
7
3
14
10
6
2
13
9
5
1


In [45]:
i = [5]

In [46]:
i

[5]

In [47]:
type(i)

list

In [48]:
i.append(8)

In [49]:
i

[5, 8]

In [112]:
a

(array([2]),)

In [51]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [52]:
ravel_array = np.ravel(a)
ravel_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [55]:
type(int(ravel_array[5]))

int

In [70]:
e

[]

In [99]:
image_count = 10
n = np.ones(image_count)

In [100]:
n

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
n[4] -= 1
order = [1,2,3,4]
print(n)
print(order)
print(n[order])
a = np.where(n==n.min())
print(a)
a[0][0]

[3. 3. 1. 3. 3. 3. 3. 3. 3. 3.]
[1, 2, 3, 4]
[3. 1. 3. 3.]
(array([2]),)


2

In [111]:
a

(array([2]),)

In [114]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [115]:
a.shape

(4, 4)

In [116]:
a.shape[0]

4

In [117]:
a.shape[0:2]

(4, 4)