In [6]:
import numpy as np

def intrange(a,b):
    x = []
    for i in range(a,b+1):
        x.append(i)
    return x

In [7]:
a = np.arange(6)

In [8]:
a2 = a[np.newaxis,:]

In [9]:
a2.shape

(1, 6)

In [13]:
a = np.array([intrange(1,5),intrange(6,10),intrange(11,15)])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
print(a[0])

[1 2 3 4 5]


In [19]:
print(a[0][2])
print(a[2][4])

3
15


In [23]:
b = np.zeros(3,2)
print(b)

TypeError: data type not understood

In [25]:
np.empty(2)

array([0., 0.])

In [29]:
a = np.array([np.zeros(3),np.ones(3),np.arange(2,10,3),np.linspace(3,10,3)])
print(a)

[[ 0.   0.   0. ]
 [ 1.   1.   1. ]
 [ 2.   5.   8. ]
 [ 3.   6.5 10. ]]
